fzf-ffprobes() utilizes now fdl(). Sort by path fiexed in fdl(). vlc-enqueue() introduced.

diff --git a/ffmpeg b/ffmpeg
--- a/ffmpeg
+++ b/ffmpeg
@@ -49,11 +49,21 @@ ffprobes() {
   done
 }
 
+if in-path vlc ; then
+
+  vlc-enqueue() {
+    local _winid
+    _winid="$(xdotool search --name 'VLC media player')"
+    [ -z "$_winid" ] || xdotool windowactivate "$_winid"
+    nohup vlc --verbose 0 --playlist-enqueue "$@" &
+  }
+
+fi
+
 fzf-ffprobes() (
   # CAUTION: For huge directory trees filtering for audio/video files will slow down loading fzf
   # list input. Use of --all avoids this but may list files not supported by ffprobe a/o vlc.
   local _all _play _sort
-  _sort="date"
   while [ $# -gt 0 ] ; do
     case "$1" in
        -a|--all) _all=y;;
@@ -68,59 +78,49 @@ fzf-ffprobes() (
   if [[ $# -gt 0 && -d "$1" ]] ; then
 
     _ffprobes-all() {
-      find-beyond-git . ! -readable -prune -o -type f -printf "%TF %TH:%TM:%02.2TS|%s|%P\n" | \
-      { case "$_sort" in
-          date) sort -t"|" -k1dr;;
-          size) sort -t"|" -k2nr;;
-             *) sort -t"|" -k3;;
-        esac
-      } | awk -F"|" '{ l=$2; d=2;
-                       if (l>1073741824) { l=l/1073741824; u="G" }
-                       else if (l>1048576) { l=l/1048576; u="M" }
-                       else if (l>1024) { l=l/1024;u="k" }
-                       else { d=0; u="" }
-                       printf "%s|%0.*f%s|%s\n",$1,d,l,u,$3
-                     }'
+      fdl --type f --no-ignore --header ${_sort:+--sort $_sort}
     }
 
     _ffprobes-filter() {
-      local _file
-      while read -r _file ; do
-        [[ "$(file -E --brief --mime "${_file##*|}")" =~ (audio|video) ]] && echo "$_file"
+      local _fdl _path
+      while read -r _fdl ; do
+        if [[ "$_fdl" =~ ^Permission ]] ; then
+          echo "$_fdl"
+        else
+          _path="$(cut -d$'\u00a0' -f 7 <<<"$_fdl" | strip_esc)"
+          [[ "$(file -E --brief --mime "$_path")" =~ (audio|video) ]] && echo "$_fdl"
+        fi
       done <<<"$(_ffprobes-all)"
     }
 
-    _vlc-enqueue() {
-      local _winid
-      _winid="$(xdotool search --name 'VLC media player')"
-      [ -z "$_winid" ] || xdotool windowactivate "$_winid"
-      nohup vlc --verbose 0 --playlist-enqueue "$@" &
-    }
-    export -f _vlc-enqueue
+    export -f vlc-enqueue
 
     cd "$1"
     myprofile _fzf
-    
-    { echo "Modified|Size|Path"
-      [ -n "$_all" ] && _ffprobes-all "$1" || _ffprobes-filter "$1"
-    } | column -t -s"|" -R 2 -l 3 | \
-    _fzf-wrapper --accept-nth '{4..}' \
+
+    { [ -n "$_all" ] && _ffprobes-all "$1" || _ffprobes-filter "$1"
+    } | \
+    _fzf-wrapper --ansi \
+                 --accept-nth 7 \
                  --bind "alt-a:clear-selection" \
-                 --bind "alt-v:execute-silent(_vlc-enqueue {+4..})+clear-selection" \
-                 --bind "enter:$([ -n "$_play" ] && echo "execute(_vlc-enqueue {+4..})+abort" || echo "accept")" \
+                 --bind "alt-v:execute(vlc-enqueue {+7})+clear-selection" \
+                 --bind "enter:$([ -n "$_play" ] && echo "execute(_vlc-enqueue {+7})+abort" || echo "accept")" \
                  --border none \
+                 --color "label:reverse" \
+                 --delimiter $'\u00a0' \
                  --exit-0 \
                  --header-lines 1 \
                  --help "Alt-a:Clear selection;Alt-i:File info;Alt-v:Play current/selected file(s) via VLC" \
-                 --list-label " Audio and video files in \"$(realpath "$1")/\" " \
+                 --list-label "[ Audio and video files in \"$(realpath "$1")/\" ]" \
                  --multi \
                  --no-sort \
-                 --preview-init "alt-i:_fzf-preview-path {4..}" \
-                 --preview-label " ffprobe output " \
+                 --preview-init "alt-i:_fzf-preview-path {7}" \
+                 --preview-label "[ File stats and ffprobe output ]" \
                  --preview-window "60%,~2:wrap" \
                  --query "$2" \
                  --print0 \
-                 --reverse | \
+                 --reverse \
+                 --with-nth 6,5,7 | \
     xargs -r0 ls
 
   else
