myprofile(): Scripts to source are now searched in "~/.config/myprofile/", "/etc/myprofile/" and "$MYPROFILE/".

diff --git a/myprofile b/myprofile
--- a/myprofile
+++ b/myprofile
@@ -1,11 +1,9 @@
 #!/usr/bin/echo "myprofile must be *sourced* by bash sessions/scripts!"
 # -*- shell-script -*-
-#
-# Without arguments all script listed in "myprofile.default" will be sourced too.
 
 myprofile() {
-  local _script _verbose _conf
-  local -a _scripts
+  local _default _dir _script _src _verbose
+  local -a _scripts _search
 
   while [ $# -gt 0 ] ; do
     case "$1" in
@@ -27,23 +25,40 @@ myprofile() {
     esac
     shift
   done
+#set -x 
+  _search=("$HOME/.config/$FUNCNAME" "/etc/$FUNCNAME" "${MYPROFILE%/*}")
 
   if [[ ${#_scripts[@]} -eq 0 && -n "$PS1" ]] ; then
-
-    _conf="$HOME/.config/$FUNCNAME/default"
-    _scripts=($(grep -v -E "^[[:space:]]*[#_]" "$([ -s "$_conf" ] && echo "$_conf" || echo "${MYPROFILE%/*}/$FUNCNAME.default")"))
-
+    for _dir in ${_search[@]} ; do
+      _default="$_dir/default"
+      if [ -s "$_default" ] ; then
+        _scripts=($(grep -v -E "^[[:space:]]*[#_]" "$_default"))
+        break
+      fi
+    done
   fi
 
   for _script in ${_scripts[@]} ; do
 
-    [ -z "$_verbose" ] || echo "Source \"$_script\"."
+    if [ -s "$_script" ] ; then
+      _src="$_script"
+    else
+      for _dir in ${_search[@]} ; do
+        _src="$_dir/$_script"
+        [ -s "$_src" ] && break
+      done
+    fi
 
-    if ! source "${MYPROFILE%/*}/$_script" ; then
-
-      echo "Load of myprofile script \"$_script\" has failed!" >&2
+    if [ ! -s "$_src" ] ; then
+      echo "Missing myprofile script \"$_script\"!" >&2
       return 1
+    fi
 
+    [ -z "$_verbose" ] || echo "Source \"$_src\"."
+
+    if ! source "$_src" ; then
+      echo "Load of myprofile script \"$_src\" has failed!" >&2
+      return 1
     fi
 
   done
